### ISSUE TITLE
Refactor Adding Additional Repos to Configuration

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#5]
Can we clean up things so if I want to add/modify additional girder servers to the App, it is in a single config file... something like

config.serverList = [  
   {"serverApiURL": "http://some/site1", "serverName": "DisplayNameForServer_A"},
   {"serverApiURL": "http://some/site2", "serverName": "DisplayNameForServer_B"},
   {"serverApiURL": "http://some/site3", "serverName": "DisplayNameForServer_C"}
 ]  

![image](https://user-images.githubusercontent.com/713166/51391232-86ad5580-1aff-11e9-8e7f-4c1bc053b914.png)

**Comment by dverkhovsky13** [comment]
Hello David. I've write an answers in documents yesterday, but I guess you didn't see it. So "I'm not quite sure of that. For add new host you need to change dropdown box and the logic which changes the main API URL. I will simplify that so you will not need to set the hostId of new host, but still you will have to set it in constants.js as a const variable with host API."

**Comment by dverkhovsky13** [comment]
As you can see in "manual changes" we've sent, you need to change 3 files for because there is functionality for selecting a host after refreshing page or even closing a browser (saved in local storage) that based on these files. So If you add this config.json file, you will also need to add this to dropdown.data, then you will have to check which hosts was selected and set the information about it to local storage, and finally, you will have to set API_URL for future requests and that's what we're doing now but w/o config.json.

**Comment by dgutman** [comment]
Yes-- that's a bit confusing...  can you refactor this so there's only a single file that needs to be modified in order to populate the dropdown?  Having to go into multiple files is confusing... also having to specify
FIRST_API_URL, SECOND_API_URL, THIRD_API_URL is also a bit verbose...

I'd rather it just take an array similar to below, and then use that for everything
config.serverList = [
{"serverApiURL": "http://some/site1", "serverName": "DisplayNameForServer_A"},
{"serverApiURL": "http://some/site2", "serverName": "DisplayNameForServer_B"},
{"serverApiURL": "http://some/site3", "serverName": "DisplayNameForServer_C"}
]


		}),
			new webpack.EnvironmentPlugin({
				FIRST_HOST_API_URL: "http://dermannotator.org:8080/api/v1",
				SECOND_HOST_API_URL: "http://candygram.neurology.emory.edu:8080/api/v1",
			})
		]
	};

**Comment by dgutman** [comment]
new features added.. now single edit in package.json
